apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wuf8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wuf8
    app.kubernetes.io/part-of: ci1t-830-0082-app
  name: devfile-sample-wuf8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wuf8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wuf8
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0082-tenant/ci1t-830-0082-app/devfile-sample-wuf8@sha256:31ba70dda40f06a153b44066f55c2100d08d4bc925bf339155f58f7586a8f2d8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
